Add intro blog post
skodjob/blog pull request #13
Opened 2024-01-25 16:54 UTC by Frawless

2024-01-25 18:38 UTC, obabec requested changes

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +It is good feeling, and we all hope, that you will enjoy our posts where we will try to provide as much information as we may, and also information that we were missing in other posts that we came ac
```suggestion
It is a good feeling, and we all hope, that you will enjoy our posts where we will try to provide as much information as we may, and also information that we were missing in other posts that we came across in the past.
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +During the years we did several talks, write some blog posts about our work, and learn a lot of cool stuff.
```suggestion
During the years we did several talks, wrote some blog posts about our work, and learned a lot of cool stuff. 
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +So we took that road and during free time we moved from regular verification to customer simulation with a lot of unknown.
```suggestion
So we took that road and during free time we moved from regular verification to customer simulation with a lot of unknowns.
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +Our existing approach was fine for verifying features, but it was usually done in small scale.
```suggestion
Our existing approach was fine for verifying features, but it was usually done in a small scale. 
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +A lot of questions suddenly comes to our minds like:
```suggestion
A lot of questions suddenly come to our minds like:
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +- how the software be behave when it will running for several weeks/months?
```suggestion
- how does the software behave when it will run for several weeks/months?
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +During Covid-19 pandemic we spent a lot of time home and during that time one of the best TV series was online - Stargate SG-1.
```suggestion
During the Covid-19 pandemic, we spent a lot of time at home and during that time one of the best TV series was online - Stargate SG-1.
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +No worries, I am not going to promote the series or spoils the plot to you!
```suggestion
No worries, I am not going to promote the series or spoil the plot for you! 
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +However, within our team we liked Teal'c character, and then it started - let's start to work on something and le'ts called it Teal'c!
```suggestion
However, within our team, we liked Teal'c character, and then it started - let's start to work on something, and let's call it Teal'c!
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +We started with an initiative that's goal was to test our projects more like customers.
```suggestion
We started with the idea to test our project in an environment that is more or less similar to what customers could be using.
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +That was enough for testing most of the features we introduced. However, at some point it started to be a little bit boring so we were thinking about some new challenge.
```suggestion
That was enough for testing most of the features we introduced. However, at some point, it started to be a little bit boring so we were thinking about some new challenge.
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +Our experience was mostly about spinning up Kubernetes cluster, deploy our project, in our case [Strimzi](https://strimzi.io/), play with it a little bit on test level, and then evaluate the state wi
```suggestion
Our experience was mostly about spinning up the Kubernetes cluster, deploying our project, in our case, [Strimzi](https://strimzi.io/), playing with it a little bit on the test level, and then evaluating the state with some results.
```

2024-01-25 18:38 UTC, obabec commented on posts/general/new-boy-in-town.md
> +The whole idea started a few years back. Our main work consists of testing system, that are running on top of Kubernetes.
```suggestion
The whole idea started a few years back. Our main work consists of finding all sorts of defaults in applications running on top of Kubernetes.
```

2024-01-26 08:40 UTC, kornys approved these changes

2024-01-26 09:03 UTC, obabec approved these changes

2024-01-26 09:04 UTC, merged